### PR TITLE
Replace Mono.Cecil with AsmResolver

### PR DESCRIPTION
**Pull request by ds5678**
This pull request replaces [Mono.Cecil](https://github.com/jbevain/cecil) with [AsmResolver](https://github.com/Washi1337/AsmResolver) as the library used for writing assemblies. Generated assemblies should be of higher quality than they were under Cecil.

### CODE REVIEW

**Comment by UlyssesWu** [comment]
I'm curious about "higher quality"...

**Comment by ds5678** [comment]
Higher quality for a couple reasons:
* AsmResolver handles assembly references better
* Generic method code is cleaner
* I fixed a couple bugs

**Comment by UlyssesWu** [comment]
Thanks for explanation. I use dnlib a lot, so I always curious if AsmResolver is a better choice. Will try it later.

**Comment by ds5678** [comment]
There was a bit of a learning curve at first, but I think it's better library than Cecil. The only downside is that it's noticeably slower. Previous runs would take under 20 minutes, but this has gone on for an hour so far.

**Comment by ds5678** [comment]
Under Cecil, the previous run took 2.53 seconds per json. Under AsmResolver, it took 9.04 seconds per json. In other words, 3.57 times longer. This is an unfortunate, but necessary, sacrifice. Hopefully, this can be reduced in future with performance profiling on AssemblyDumper and AsmResolver.

**Pull request merged**
